name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd taxonomy-synthesis
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run pre-commit hooks
        run: |
          cd taxonomy-synthesis
          poetry run pre-commit run --all-files

      - name: Run tests with pytest
        run: |
          cd taxonomy-synthesis
          poetry run pytest

      - name: Bump version and create a GitHub release
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          cd taxonomy-synthesis
          poetry run bump2version patch --allow-dirty
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Publish to PyPI
        if: github.event_name == 'push'
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          cd taxonomy-synthesis
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build --username __token__ --password $PYPI_TOKEN